
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author emma
 */
public class MyOrderedMedicine extends javax.swing.JFrame {

    String driver ="com.mysql.jdbc.Driver";
    String url = "jdbc:mysql://localhost:3306/db";
    String user = "root";
    String pass = "immanual";
    int paId;
    Patient pa;
    /**
     * Creates new form MyOrderedMedicine
     */
    public MyOrderedMedicine() {
        initComponents();
        
    }

    MyOrderedMedicine(Patient pa) {
        initComponents();
        this.pa=pa;
        paId=pa.getId();
        showMyOrders();
    }

    ArrayList<OrderList> orderList(){
        ArrayList<OrderList> order_List=new ArrayList<> ();
        try{
            Class.forName(driver);
            Connection con=DriverManager.getConnection(url,user,pass);
            String sql="select * from OrderedMedicine where customerId="+paId;
            ResultSet rs;
            rs=con.prepareStatement(sql).executeQuery();
            while(rs.next())
            {
                int id=rs.getInt("id");
                int pharmacistId=rs.getInt("pharmacistId");
                int customerId=rs.getInt("customerId");
                String customerName=rs.getString("customerName");
                String customerAddress=rs.getString("customerAddress");
                String medicineName=rs.getString("medicineName");
                int unitOrdered=rs.getInt("unitOrdered");
                String orderStatus=rs.getString("status");
                String deliveryTime=rs.getString("deliveryTime");
                OrderList order;
                
                    order= new OrderList(id,pharmacistId,customerId,customerName,customerAddress,medicineName,unitOrdered,orderStatus,deliveryTime);
                    order_List.add(order);
                }
            }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Not working","Alert",JOptionPane.WARNING_MESSAGE);
        }
            return order_List;
        }
    
    public void showMyOrders(){
        ArrayList<OrderList> orderslist= orderList();
     
      DefaultTableModel model = (DefaultTableModel) PatientOrderTable.getModel();
        Object[] row = new Object[7];
        orderslist.stream().map((orderslist1) -> {
            row[0] = orderslist1.getId();
            return orderslist1;
        }).map((orderslist1) -> {
            row[1] = orderslist1.getMedicineName();
            return orderslist1;
        }).map((orderslist1) -> {
            row[2] = orderslist1.getUnitOrdered();
            return orderslist1;
        }).map((orderslist1) -> {
            row[3] = orderslist1.getOrderStatus();
            return orderslist1;
        }).map((orderslist1) -> {
            row[4] = orderslist1.getDeliveryTime();
            return orderslist1;
        }).forEach((_item) -> {
            model.addRow(row);
        });  
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PatientOrderTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PatientOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "MedicineName", "Unit Ordered", "Delivery Status", "Estimated Delivery Time"
            }
        ));
        jScrollPane1.setViewportView(PatientOrderTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyOrderedMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyOrderedMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyOrderedMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyOrderedMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyOrderedMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PatientOrderTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
